# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

plugins:

google_analytics_id:

# HTML Title
title: "WatchOut! IITR Linktree"

# Avatar image path
avatar: "./images/profile.jpeg"

# Name section text
name: "WatchOut! IIT Roorkee"

# Tagline section text
tagline: >-
  IIT Roorkee's official student run media body

# List of links
links:
  - link:
      icon: "fa-solid fa-file"
      text: "Placement Diary: Aayushi Khandelwal"
      url: "https://drive.google.com/file/d/1SHN8i4hWy1H2EfXBtojCNgTo8gK_NOG7/view?usp=drive_link"
      alt: "Placement Diary: Aayushi Khandelwal"
      title: "Placement Diary: Aayushi Khandelwal"
      target: "_blank"
  - link:
      icon: "fa-solid fa-chart-line"
      text: "Placements Decoded (2024–2025)"
      url: "https://watchout.iitr.ac.in/2025/06/placement-analysis-2025"
      alt: "Placement Analysis 2025"
      title: "Placement Analysis 2025"
      target: "_blank"
  - link:
      icon: "fa-solid fa-pen"
      text: "Form for Memoirs"
      url: "https://forms.gle/j8KBXHgGGb1tvN9Q6"
      alt: "Memoir Form"
      title: "Memoir Form"
      target: "_blank"
  - link:
      icon: "fa-solid fa-briefcase"
      text: "Internship Report: First Foot Forward"
      url: "https://watchout.iitr.ac.in/2025/04/intern-analysis"
      alt: "Internship Analysis 2025"
      title: "Internship Analysis 2025"
      target: "_blank"
  - link:
      icon: "fa-solid fa-book-open"
      text: "Memoir: My Reason Why - Ashita Nihore"
      url: "https://drive.google.com/file/d/1cQGTBMR7nJF9EGuK5KYBrz1R3HH68DZj/view?usp=sharing"
      alt: "Ashita Nihore Memoir"
      title: "Ashita Nihore Memoir"
      target: "_blank"
  - link:
      icon: "fa-brands fa-notion"
      text: "Notion Workspace - Recruitments"
      url: "https://juniper-filament-054.notion.site/WatchOut-Recruitments-e2cbf86d5f7146a8a7fb25d1a65b3525"
      alt: "WatchOut Notion"
      title: "WatchOut Recruitments Notion"
      target: "_blank"
  - link:
      icon: "fa-solid fa-chart-pie"
      text: "Placement Analysis (2023–2024)"
      url: "http://watchout.iitr.ac.in/2024/09/Placement-Analysis-2024"
      alt: "Placement Analysis 2024"
      title: "Placement Analysis 2024"
      target: "_blank"
  - link:
      icon: "fa-solid fa-book"
      text: "Memoir: Your Green Flag - Abby"
      url: "https://drive.google.com/file/d/1InR0R5yRRFbYCHSA14rwzzE1MuEHHI9i/view?usp=sharing"
      alt: "Abby Memoir"
      title: "Abby Memoir"
      target: "_blank"
  - link:
      icon: "fa-solid fa-file-lines"
      text: "Memoir: Finding Neko - Nikita Tripathi"
      url: "https://docs.google.com/document/d/1duP5reN3-dDqDu_ZRbAFLh9_jnEg2nRyqda9xl6pA9k/edit?usp=drive_link"
      alt: "Nikita Tripathi Memoir"
      title: "Nikita Tripathi Memoir"
      target: "_blank"
  - link:
      icon: "fa-solid fa-code-branch"
      text: "Branch Change - Clearing the Mist"
      url: "http://watchout.iitr.ac.in/2023/02/branch-change"
      alt: "Branch Change Guide"
      title: "Branch Change Guide"
      target: "_blank"
  - link:
      icon: "fa-solid fa-diagram-project"
      text: "Guide to Branches '24"
      url: "https://drive.google.com/file/d/1WZCxniQTMcfk9m6QgHCPxs9h4-AdcuOS/view?usp=sharing"
      alt: "Branches Guide 2024"
      title: "Branches Guide 2024"
      target: "_blank"

# List of social media links
socials:
  - social:
      icon: "fa-brands fa-facebook"
      url: "https://www.facebook.com/watchoutiitr/"
      title: "WatchOut's Facebook"
      alt: "WatchOut's Facebook"
      target: "_blank"
  - social:
      icon: "fa-brands fa-instagram"
      url: "https://instagram.com/watchoutiitr"
      title: "WatchOut's Instagram"
      alt: "WatchOut's Instagram"
      target: "_blank"
  - social:
      icon: "fa-brands fa-youtube"
      url: "https://youtube.com/channel/UCthZ7tKOzy4EJpuVxtdcp1A"
      title: "WatchOut's YouTube"
      alt: "WatchOut's YouTube"
      target: "_blank"
  - social:
      icon: "fa-brands fa-twitch"
      url: "https://www.twitch.tv/watchoutiitr"
      title: "WatchOut's Twitch"
      alt: "WatchOut's Twitch"
      target: "_blank"
  - social:
      icon: "fa-solid fa-envelope"
      url: "mailto:watchout@iitr.ac.in"
      title: "Email: watchout@iitr.ac.in"
      alt: "watchout@iitr.ac.in"
      target: "_blank"
  - social:
      icon: "fa-brands fa-x-twitter"
      url: "https://x.com/watchoutiitr"
      title: "WatchOut's X"
      alt: "WatchOut's X"
      target: "_blank"

# Footer text
footer: >
  Follow us on Instagram or Facebook to keep getting our updates!

# Footer copyright message
copyright: >
  © 2025  <a href="http://watchout.iitr.ac.in" target="_blank">WatchOut! IITR</a>. Powered by <a href="https://github.com/watchoutnewsagency/linktree" target="_blank">linkyee</a>
